### PR TITLE
Some English language updates and corrections

### PR DESCRIPTION
**Pull request by mcnewton**
English is not a nice language, I'm sure :smile:. Make some corrections (especially e.g. "the" and use of plurals) and a few other updates to make things tidier, or change to more common usage.

I have this as a set of 38 individual commits if it would be helpful, instead of all in one.

### CODE REVIEW

**Comment by bilbo-the-hobbit** [comment]
hello @mcnewton 

thank for the review much appreciated, i would prefer the 38 individuals commit instead of one to make the review easier

**Comment by mcnewton** [comment]
OK no worries! I'll update the PR shortly.

**Comment by mcnewton** [comment]
That is a lot of lipstick :grin:. Hope it's clearer now.

**Comment by bilbo-the-hobbit** [comment]
hello @mcnewton 

thanks for this pr, sorry it take so long to act on it :) it's now merge into FusionDirectory 1.4

https://gitlab.fusiondirectory.org/fusiondirectory/fd/-/issues/6245

Cheers

**Pull request closed without merging**
