### PR TITLE
colored user icons

### PR DESCRIPTION
**Pull request by Animtim**

### CODE REVIEW

**Comment by bilbo-the-hobbit** [comment]
hello,

integrated

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

commited to 1.0.12-fixes

**Comment by Animtim** [comment]
Fix the plugin section titles as requested, and a some border colors as well.

**Comment by bilbo-the-hobbit** [comment]
hello,

commited into 1.0.12-fixes

Cheers

**Comment by bilbo-the-hobbit** [comment]
hello,

just checked and it look well now for the css 

Cheers

**Comment by bilbo-the-hobbit** [comment]
Hello,

closing this pull request too keep stuff clean

**Pull request closed without merging**
